// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moskdrumibgjtdjlorwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vc2tkcnVtaWJnanRkamxvcnd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODM5NTcsImV4cCI6MjA2ODk1OTk1N30.jqtq7SCb6xm-mvlHy-iTPOqEe3Jnbvg06diW84XGdXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});